In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/Salary_Data.csv")
print(df)

In [ ]:
x = df.iloc[:,0].values.reshape(df.shape[0],1)
y = df.iloc[:,1].values 
# Why reshape x? Because the fit function takes input as a 2D array.
# This is because there are multiple features/inputs in real world data

In [ ]:
x.shape

(30, 1)

In [ ]:
x

In [ ]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Lin = LinearRegression()

In [ ]:
Lin.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = Lin.predict(x_test)

In [ ]:
y_pred

array([37733.34168564, 81405.28234431, 35792.36654525, 33851.39140487,
       74611.86935296, 42585.7795366 ])

In [ ]:
y_test

array([37731., 93940., 46205., 39343., 83088., 43525.])

In [ ]:
abs(y_test - y_pred).mean()

6309.442083607349